import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const exportReportPDF = (report) => {

  const doc = new jsPDF();

  const today = new Date();

  // HEADER
  doc.setFontSize(22);
  doc.setTextColor(30, 41, 59);

  doc.text(
    "WanderEscape",
    14,
    20
  );

  doc.setFontSize(14);

  doc.text(
    "Tourism Management Report",
    14,
    30
  );

  doc.line(14, 35, 195, 35);

  // DATE
  doc.setFontSize(11);

  doc.text(
    `Generated Date: ${today.toLocaleDateString()}`,
    14,
    45
  );

  doc.text(
    `Generated Time: ${today.toLocaleTimeString()}`,
    14,
    52
  );

  // SUMMARY
  doc.setFontSize(16);

  doc.text(
    "Report Summary",
    14,
    68
  );

  autoTable(doc, {
    startY: 75,

    head: [["Metric", "Value"]],

    body: [
      [
        "Total Revenue",
        `$${report.totalRevenue}`
      ],
      [
        "Total Bookings",
        report.totalBookings
      ],
      [
        "Approved",
        report.approved
      ],
      [
        "Pending",
        report.pending
      ],
      [
        "Rejected",
        report.rejected
      ],
    ],
  });

  // TRANSACTION TABLE
  autoTable(doc, {
    startY:
      doc.lastAutoTable.finalY + 15,

    head: [[
      "REF",
      "Customer",
      "Amount",
      "Status",
      "Date"
    ]],

    body:
      report.recentTransactions?.map(
        (item) => [
          `#${item.booking_id}`,
          item.full_name,
          `$${item.amount}`,
          item.payment_status,
          new Date(
            item.payment_date
          ).toLocaleDateString(),
        ]
      ) || [],
  });

  // FOOTER
  doc.setFontSize(10);

  doc.text(
    "Generated by WanderEscape Admin Dashboard",
    14,
    285
  );

  doc.save(
    `WanderEscape_Report_${today
      .toISOString()
      .slice(0, 10)}.pdf`
  );
};